version: "3"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./Backend
    volumes:
      - /app/node_modules
      - ./Backend:/app
    environment:
      - PORT=5000
      - ORIGIN=http://localhost:3000
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./front/demo
    volumes:
      - /app/node_modules
      - ./front/demo:/app
    environment:
      - WDS_SOCKET_PORT=0
  